"""
Driver router — mobile app endpoints.

- GET  /driver/status     → driver info + active trip state
- POST /driver/trip/start → start a new trip (with odometer image upload)
- POST /driver/trip/end   → end the active trip (with odometer image upload)
"""

import uuid
from datetime import datetime, timezone, date

from fastapi import APIRouter, Depends, File, Form, Query, UploadFile
from sqlalchemy.orm import Session, joinedload

from app.dependencies import get_db, require_driver
from app.models.user import User
from app.models.vehicle import Vehicle
from app.models.driver_vehicle import DriverVehicleAssignment
from app.models.trip import Trip, TripStatus
from app.schemas.trip import DriverStatusResponse, DriverTripListResponse
from app.services.cloudinary_service import upload_odometer_image
from app.services.trip_service import get_open_trip, apply_exceptions
from app.services.audit_service import log_action
from app.utils.exceptions import not_found, conflict, bad_request

router = APIRouter(prefix="/driver", tags=["Driver App"])


# ── Helpers ───────────────────────────────────────────────

def _get_active_assignment(db: Session, driver_id: uuid.UUID) -> DriverVehicleAssignment | None:
    """Return the driver's current active vehicle assignment."""
    return (
        db.query(DriverVehicleAssignment)
        .filter(
            DriverVehicleAssignment.driver_id == driver_id,
            DriverVehicleAssignment.is_active == True,
        )
        .first()
    )


# ── GET /driver/status ───────────────────────────────────

@router.get("/status", response_model=DriverStatusResponse)
def driver_status(
    db: Session = Depends(get_db),
    driver: User = Depends(require_driver),
):
    """
    Returns current driver info (Name, Vehicle Number, Vehicle Model)
    and active trip status to determine mobile app UI button states.
    """
    assignment = _get_active_assignment(db, driver.id)
    vehicle = assignment.vehicle if assignment else None

    open_trip = get_open_trip(db, str(driver.id))

    return DriverStatusResponse(
        driver_name=driver.full_name,
        vehicle_plate_number=vehicle.plate_number if vehicle else None,
        vehicle_model=f"{vehicle.make} {vehicle.model}" if vehicle else None,
        has_active_trip=open_trip is not None,
        active_trip_id=open_trip.id if open_trip else None,
    )


# ── GET /driver/trips ────────────────────────────────────

@router.get("/trips", response_model=list[DriverTripListResponse])
def get_my_trips(
    status: TripStatus | None = Query(None, description="Filter by trip status: OPEN or COMPLETED"),
    limit: int = Query(50, ge=1, le=200, description="Max trips to return"),
    offset: int = Query(0, ge=0, description="Trips to skip (pagination)"),
    db: Session = Depends(get_db),
    driver: User = Depends(require_driver),
):
    """
    Get all trips for the authenticated driver, ordered newest first.

    - Optionally filter by `status` (OPEN or COMPLETED).
    - Supports pagination via `limit` and `offset`.
    """
    query = (
        db.query(Trip)
        .options(joinedload(Trip.vehicle))
        .filter(Trip.driver_id == driver.id)
    )

    if status is not None:
        query = query.filter(Trip.status == status)

    return (
        query
        .order_by(Trip.start_server_time.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )


# ── POST /driver/trip/start ──────────────────────────────

@router.post("/trip/start", status_code=201)
async def start_trip(
    latitude: float = Form(...),
    longitude: float = Form(...),
    location: str = Form(...),
    start_odometer: float = Form(...),
    route_notes: str = Form(None),
    odometer_image: UploadFile = File(...),
    db: Session = Depends(get_db),
    driver: User = Depends(require_driver),
):
    """
    Start a new trip.

    - Accepts an UploadFile for the odometer image → uploads to Cloudinary.
    - Records latitude, longitude, GPS accuracy, start odometer, and route notes.
    - Sets status to OPEN.

    CRUCIAL RULES:
    - Start Date and Start Server Time are generated by the FastAPI backend.
    - Rejects the request if the driver already has an OPEN trip (HTTP 409).
    """
    # ── Guard: no overlapping trips ───────────────────────
    existing = get_open_trip(db, str(driver.id))
    if existing:
        raise conflict(
            "You already have an active trip. End the current trip before starting a new one."
        )

    # ── Guard: driver must have an assigned vehicle ──────
    assignment = _get_active_assignment(db, driver.id)
    if not assignment:
        raise bad_request("No vehicle assigned. Contact your administrator.")

    # ── Upload odometer image to Cloudinary ──────────────
    image_url = await upload_odometer_image(odometer_image, folder="odometer_images/start")

    # ── Create trip with server-generated timestamps ─────
    now = datetime.now(timezone.utc)
    trip = Trip(
        driver_id=driver.id,
        vehicle_id=assignment.vehicle_id,
        start_date=now.date(),
        start_server_time=now,
        start_latitude=latitude,
        start_longitude=longitude,
        start_location=location,
        start_odometer=start_odometer,
        start_odometer_image=image_url,
        route_notes=route_notes,
        status=TripStatus.OPEN,
    )
    db.add(trip)

    log_action(
        db,
        user_id=str(driver.id),
        action="START_TRIP",
        new_value={
            "trip_id": str(trip.id) if trip.id else "pending",
            "start_odometer": start_odometer,
            "server_time": now.isoformat(),
        },
    )

    db.commit()
    db.refresh(trip)

    return {
        "message": "Trip started successfully.",
        "trip_id": str(trip.id),
        "start_server_time": trip.start_server_time.isoformat(),
    }


# ── POST /driver/trip/end ────────────────────────────────

@router.post("/trip/end")
async def end_trip(
    latitude: float = Form(...),
    longitude: float = Form(...),
    location: str = Form(...),
    end_odometer: float = Form(...),
    odometer_image: UploadFile = File(...),
    db: Session = Depends(get_db),
    driver: User = Depends(require_driver),
):
    """
    End the driver's active trip.

    - Accepts an UploadFile for the end odometer image → uploads to Cloudinary.
    - Records end location and end odometer.
    - Updates status to COMPLETED.
    - Backend calculates KM Used and Working Hours based on Server Time.
    - Automatically flags as EXCEPTION if business rules are violated.
    """
    # ── Guard: must have an open trip ────────────────────
    trip = get_open_trip(db, str(driver.id))
    if not trip:
        raise not_found("No active trip found to end.")

    # ── Upload end odometer image ────────────────────────
    image_url = await upload_odometer_image(odometer_image, folder="odometer_images/end")

    # ── Update trip with server-generated timestamps ─────
    now = datetime.now(timezone.utc)
    trip.end_date = now.date()
    trip.end_server_time = now
    trip.end_latitude = latitude
    trip.end_longitude = longitude
    trip.end_location = location
    trip.end_odometer = end_odometer
    trip.end_odometer_image = image_url
    trip.status = TripStatus.COMPLETED

    # ── Auto-detect exceptions ───────────────────────────
    apply_exceptions(trip)

    log_action(
        db,
        user_id=str(driver.id),
        action="END_TRIP",
        new_value={
            "trip_id": str(trip.id),
            "end_odometer": end_odometer,
            "km_used": trip.km_used,
            "working_hours": trip.working_hours,
            "verification_status": trip.verification_status.value,
            "server_time": now.isoformat(),
        },
    )

    db.commit()
    db.refresh(trip)

    return {
        "message": "Trip completed successfully.",
        "trip_id": str(trip.id),
        "km_used": trip.km_used,
        "working_hours": trip.working_hours,
        "verification_status": trip.verification_status.value,
        "exception_reason": trip.exception_reason,
    }
