"""
Trip Pydantic schemas — Start, End, Response, Filters.
"""

import uuid
from datetime import datetime, date
from pydantic import BaseModel

from app.models.trip import TripStatus, VerificationStatus


# ── Driver App Request Schemas ────────────────────────────

class TripStartRequest(BaseModel):
    """
    Sent by the driver mobile app when starting a trip.
    Note: start_date and start_server_time are generated by the backend.
    The odometer image is sent as UploadFile (not in this schema).
    """
    latitude: float
    longitude: float
    location: str
    start_odometer: float


class TripEndRequest(BaseModel):
    """
    Sent by the driver mobile app when ending a trip.
    The odometer image is sent as UploadFile (not in this schema).
    """
    latitude: float
    longitude: float
    location: str
    end_odometer: float
    route_notes: str | None = None


# ── Admin Filter Schema ──────────────────────────────────

class TripFilterParams(BaseModel):
    date_from: date | None = None
    date_to: date | None = None
    driver_id: uuid.UUID | None = None
    vehicle_id: uuid.UUID | None = None
    plate_number: str | None = None
    status: TripStatus | None = None
    verification_status: VerificationStatus | None = None


# ── Response Schemas ──────────────────────────────────────

class DriverBrief(BaseModel):
    id: uuid.UUID
    full_name: str
    mobile_number: str

    model_config = {"from_attributes": True}


class VehicleBrief(BaseModel):
    id: uuid.UUID
    plate_number: str
    make: str
    model: str

    model_config = {"from_attributes": True}


class TripListResponse(BaseModel):
    id: uuid.UUID
    driver: DriverBrief
    vehicle: VehicleBrief
    start_date: date
    start_server_time: datetime
    end_server_time: datetime | None = None
    start_location: str
    end_location: str | None = None
    start_odometer: float
    end_odometer: float | None = None
    status: TripStatus
    verification_status: VerificationStatus
    route_notes: str | None = None
    start_odometer_image: str
    end_odometer_image: str | None = None
    km_used: float | None = None
    working_hours: float | None = None
    working_hours_formatted: str | None = None
    overtime_hours: float | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


class TripDetailResponse(BaseModel):
    id: uuid.UUID
    driver: DriverBrief
    vehicle: VehicleBrief

    # Start metrics
    start_date: date
    start_server_time: datetime
    start_latitude: float
    start_longitude: float
    start_location: str
    start_odometer: float
    start_odometer_image: str

    # End metrics
    end_date: date | None = None
    end_server_time: datetime | None = None
    end_latitude: float | None = None
    end_longitude: float | None = None
    end_location: str | None = None
    end_odometer: float | None = None
    end_odometer_image: str | None = None

    # Computed
    km_used: float | None = None
    working_hours: float | None = None
    working_hours_formatted: str | None = None
    overtime_hours: float | None = None

    # Meta
    route_notes: str | None = None
    status: TripStatus
    verification_status: VerificationStatus
    exception_reason: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


# ── Driver Status Response ───────────────────────────────

class DriverStatusResponse(BaseModel):
    driver_name: str
    vehicle_plate_number: str | None = None
    vehicle_model: str | None = None
    has_active_trip: bool
    active_trip_id: uuid.UUID | None = None


# ── Driver Trip History Response ─────────────────────────

class DriverTripListResponse(BaseModel):
    """Returned by GET /driver/trips — trip history for the authenticated driver."""
    id: uuid.UUID
    vehicle: VehicleBrief

    # Start
    start_date: date
    start_server_time: datetime
    start_odometer: float
    start_odometer_image: str
    start_latitude: float
    start_longitude: float
    start_location: str

    # End (null if trip still OPEN)
    end_date: date | None = None
    end_server_time: datetime | None = None
    end_odometer: float | None = None
    end_odometer_image: str | None = None
    end_latitude: float | None = None
    end_longitude: float | None = None
    end_location: str | None = None

    # Computed
    km_used: float | None = None
    working_hours: float | None = None
    working_hours_formatted: str | None = None
    overtime_hours: float | None = None

    # Meta
    route_notes: str | None = None
    status: TripStatus
    verification_status: VerificationStatus
    exception_reason: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}
